apiVersion: v1
kind: Pod
metadata:
  name: rootless-no-legion-pod
  annotations:
    container.apparmor.security.beta.kubernetes.io/buildkit-container: unconfined
spec:
  containers:
  - name: buildkit-container
    image: showpune/buildkit-test:simple
    imagePullPolicy: Always
    securityContext:
      seccompProfile:
        type: Unconfined
      runAsUser: 1000
      runAsGroup: 1000
    env:
    - name: DOCKER_USERNAME
      valueFrom:
        secretKeyRef:
          name: dockerhub-credentials
          key: .dockerconfigjson
    - name: DOCKER_PASSWORD
      valueFrom:
        secretKeyRef:
          name: dockerhub-credentials
          key: .dockerconfigjson    
    resources:
      limits:
        cpu: "1"
        memory: "512Mi"
      requests:
        cpu: "0.5"
        memory: "256Mi"
