apiVersion: batch/v1
kind: Job
metadata:
  name: root-job
spec:
  template:
    spec:
      volumes:
      - name: docker-volume
        secret:
          secretName: dockerhub-credentials
          items:
          - key: .dockerconfigjson
            path: config.json
      restartPolicy: Never
      containers:
      - name: buildkit-container
        image: showpune/buildkit-test:root
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: DOCKER_CONFIG
          value: /etc/.docker
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        volumeMounts:
        - name: docker-volume
          mountPath: /etc/.docker
