apiVersion: batch/v1
kind: Job
metadata:
  name: rootless-addcap-nolegion-job
  labels:
    type: buildkit-test
spec:
  template:
    spec:
      volumes:
      - name: docker-volume
        secret:
          secretName: dockerhub-credentials
          items:
          - key: .dockerconfigjson
            path: config.json
      restartPolicy: Never
      containers:
      - name: buildkit-container
        image: showpune/buildkit-test:rootless
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            - CHOWN
            - SETUID
            - SETGID
            - DAC_OVERRIDE
            - FOWNER
            - SETFCAP
            - AUDIT_WRITE
            - MKNOD
            - SYS_CHROOT
            - NET_RAW
            - SETPCAP
            - KILL
            - FSETID
        env:
        - name: DOCKER_CONFIG
          value: /etc/.docker
        resources:
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        volumeMounts:
        - name: docker-volume
          mountPath: /etc/.docker
